# Site Settings
title: Github Portfolio Site
email: u1167937@alumni.hud.ac.uk
description: >
  Github site made with jekyll to show my portfolio.
baseurl: ""
url: "https://thisisatest1990.github.io/"
